drop table if exists objects_to_events;
drop table if exists moving_characteristics;
drop table if exists static_characteristics;
drop table if exists events;
drop table if exists objects;

create table objects (
    obj_id bigint generated by default as identity primary key,
    obj_name varchar(255) not null unique,
    obj_type integer not null,
    obj_catalog_id varchar(255),
    obj_found_date date,
    obj_found_name varchar(255),
    obj_mass numeric(38, 10),
    obj_notes varchar(2000),
    star_spectre char(1),
    star_light varchar(255),
    star_count integer,
    nebula_type varchar(255),
    galaxy_type varchar(255),
    planet_type varchar(255),
    planet_parent_star bigint,
    satellite_type varchar(255),
    satellite_parent_planet bigint,
    asteroid_spectre varchar(255),
    asteroid_group varchar(255),
    comet_type varchar(255),
    comet_class varchar(255),
    meteor_shower_intensity varchar(255),
    meteor_shower_parent bigint
);

alter table objects
    add constraint fk_objects_planet_parent
    foreign key (planet_parent_star) references objects(obj_id);

alter table objects
    add constraint fk_objects_satellite_parent
    foreign key (satellite_parent_planet) references objects(obj_id);

alter table objects
    add constraint fk_objects_meteor_parent
    foreign key (meteor_shower_parent) references objects(obj_id);

create table static_characteristics (
    object_obj_id bigint primary key,
    sc_right_ascension real not null,
    sc_declension real not null,
    sc_sun_distance bigint not null,
    sc_constellation varchar(255) not null
);

alter table static_characteristics
    add constraint fk_static_characteristics_object
    foreign key (object_obj_id) references objects(obj_id);

create table moving_characteristics (
    object_obj_id bigint primary key,
    mc_semiaxis bigint not null,
    mc_eccentricity real not null,
    mc_inclination real not null,
    mc_longitude_of_asc_angle real not null,
    mc_min_velocity integer not null,
    mc_max_velocity integer not null,
    mc_min_light integer not null,
    mc_max_light integer not null
);

alter table moving_characteristics
    add constraint fk_moving_characteristics_object
    foreign key (object_obj_id) references objects(obj_id);

create table events (
    eve_id bigint generated by default as identity primary key,
    eve_name varchar(255) not null unique,
    eve_type varchar(255) not null,
    eve_period varchar(255),
    eve_start date,
    eve_end date,
    eve_notes varchar(2000)
);

create table objects_to_events (
    o2e_id bigint generated by default as identity primary key,
    o2e_object_id bigint not null,
    o2e_event_id bigint not null,
    role varchar(255) not null
);

alter table objects_to_events
    add constraint fk_objects_to_events_object
    foreign key (o2e_object_id) references objects(obj_id);

alter table objects_to_events
    add constraint fk_objects_to_events_event
    foreign key (o2e_event_id) references events(eve_id);
